services:
  - type: web
    name: linkedin-ai-news
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEEPSEEK_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 