name: Daily LinkedIn Post

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 09:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run posting script
      env:
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        LINKEDIN_PERSON_ID: ${{ secrets.LINKEDIN_PERSON_ID }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: python ai_news_poster.py 